version: '3.4'

services:
  aiocore.web:
    image: ${DOCKER_REGISTRY-}aiocoreweb
    build:
      context: .
      dockerfile: src/AioCore.Hosted/AioCore.Web/Dockerfile
  
  aiocore.api:
    image: ${DOCKER_REGISTRY-}aiocoreapi
    build:
      context: .
      dockerfile: src/AioCore.Hosted/AioCore.API/Dockerfile
