name: Docker
on:
  push:
    branches: [ dev ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./src/AioCore.API/
          file: ./src/AioCore.API/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: aiocore/aiocore-backend

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
