name: Docker

on:
  push:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.3.21202.5

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Compose build aiocore-backend
      run: sudo -E docker-compose build aiocore-backend
      working-directory: .
      shell: bash

    - name: Compose push aiocore-backend
      run: sudo -E docker-compose push aiocore-backend
      working-directory: .
      shell: bash